[package]
name = "protos"
version = "0.0.0"
edition = "2018"

[lib]
path = "lib.rs"

[dependencies]
protobuf = "2.0"

[build-dependencies]
protoc = "2.0"
protobuf-codegen-pure = "2.0"
npm_rs = "0.2"
